### PR TITLE
add email validation

### PR DESCRIPTION
**Pull request by emranpy**

### CODE REVIEW

**Review by GiovanniBruno22 — APPROVED** [review]
Wow nicely done! thanks a lot 🙂

**Review by GiovanniBruno22 — CHANGES_REQUESTED** [review]
Could you remove the __pycache__folder that got stuck in this PR please? 🙂

**Comment by emranpy** [comment]
sure yea

**Comment by emranpy** [comment]
done check it out

**Comment by GiovanniBruno22** [comment]
Perfect, thank you so much!

**Review by GiovanniBruno22 — APPROVED** [review]

**Pull request merged**
